services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inclusive-ai-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    restart: always
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
